- name: Install Docker.
  community.general.pacman:
    name: "{{ package }}"
    state: present
  loop:
    - docker
    - pigz
    - btrfs-progs
    - docker-compose
    - python-docker

- name: Start docker.
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: true
