- name: Install Docker.
  community.general.pacman:
    name:
      - docker
      - pigz
      - btrfs-progs
      - docker-compose
      - python-docker
    state: present

- name: Start docker.
  ansible.builtin.systemd:
    name: docker.service
    state: started
    enabled: true
