- name: Include tasks.
  ansible.builtin.include_tasks:
    file: "{{ tasks }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  loop_control:
    loop_var: tasks

- name: Add users to docker group.
  ansible.builtin.user:
    append: true
    groups:
      - docker
    name: "{{ user }}"
  loop: "{{ docker_users }}"
  loop_control:
    loop_var: user

- name: Flush handlers.
  ansible.builtin.meta: flush_handlers
