- name: Ensure old docker packages are not installed.
  ansible.builtin.package:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
      - podman
      - runc
    state: absent

- name: Add Docker GPG key.
  ansible.builtin.rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present

- name: Add Docker repository.
  get_url:
    url: "https://download.docker.com/linux/{{ (ansible_distribution == 'Fedora') | ternary('fedora', 'centos') }}/docker-ce.repo"
    dest: "/etc/yum.repos.d/docker-ce.repo"
    owner: root
    group: root
    mode: 0644

- name: Install docker packages.
  ansible.builtin.package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - container-selinux
    state: present
  notify: Restart Docker.

- name: Ensure Docker is started and enabled at boot.
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
