name: CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
      - name: Run ansible-lint
        run: |
          ansible-lint -v --show-relpath
      - name: Run yamllint
        run: |
          yamllint .
  # test:
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       include:
  #         - image: fabiankoehler/ubuntu1804-ansible:latest
  #         # - image: fabiankoehler/archlinux-ansible:latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up Python 3.9
  #       uses: actions/setup-python@v2
  #       with:
  #         python-version: 3.9
  #     - uses: actions/cache@v2
  #       with:
  #         path: ~/.cache/pip
  #         key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         python -m pip install -r requirements.txt
  #     - name: Run Molecule tests.
  #       run: molecule test
  #       env:
  #         PY_COLORS: "1"
  #         ANSIBLE_FORCE_COLOR: "1"
  #         MOLECULE_IMAGE: ${{ matrix.image }}
